export default {
    //getters
    GET_VIEW_SCHEDULE_LIST: 'schedules/GET_VIEW_SCHEDULE_LIST',
    GET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'schedules/GET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    GET_NEW_SCHEDULE_MODAL_VISIBILITY: 'schedules/GET_NEW_SCHEDULE_MODAL_VISIBILITY',

    //mutation
    SET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'schedules/SET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    SET_NEW_SCHEDULE_MODAL_VISIBILITY: 'schedules/SET_NEW_SCHEDULE_MODAL_VISIBILITY',
}