# Generated by Django 3.2.3 on 2023-09-05 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Clinic Name')),
                ('date_established', models.DateTimeField(blank=True, default='', null=True, verbose_name='Date Established')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('description', models.CharField(blank=True, default='', max_length=400, verbose_name='Clinic Description')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
