# Generated by Django 3.2.3 on 2023-09-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinics_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinics',
            old_name='owner_user',
            new_name='user',
        ),
    ]
