export default {
    //getters
    GET_CLIENTS: 'clients/GET_CLIENTS',
    GET_VIEW_CLIENT_DETAILS: 'clients/GET_VIEW_CLIENT_DETAILS',
    GET_CLIENT_MODAL_VISIBILITY: 'clients/GET_CLIENT_MODAL_VISIBILITY',
    GET_CLIENT_FORM_FIELDS: 'clients/GET_CLIENT_FORM_FIELDS',
    GET_FETCHING_CLIENTS_STATUS: 'clients/GET_FETCHING_CLIENTS_STATUS',
    GET_FETCHING_CLIENT_DETAILS_STATUS: 'clients/GET_FETCHING_CLIENT_DETAILS_STATUS',
    GET_CLIENT_APPOINTMENT_TODAY: 'clients/GET_CLIENT_APPOINTMENT_TODAY',
    GET_APPOINTMENTS: 'clients/GET_APPOINTMENTS',
    GET_CLIENT_APPOINTMENTS_COUNT: 'clients/GET_CLIENT_APPOINTMENTS_COUNT',

    //mutation
    SET_CLIENT_MODAL_VISIBILITY: 'clients/SET_CLIENT_MODAL_VISIBILITY',
    SET_MODAL_FIELD_SINGLE_VALUE: 'clients/SET_MODAL_FIELD_SINGLE_VALUE',
    SET_APPOINTMENTS_TODAY_COMMENT: 'clients/SET_APPOINTMENTS_TODAY_COMMENT',
    SET_APPOINTMENTS: 'clients/SET_APPOINTMENTS',
    SET_APPOINTMENTS_DETAILS_MODAL: 'clients/SET_APPOINTMENTS_DETAILS_MODAL',
    SET_APPOINTMENTS_TODAY_COMMENT_HIDE_STATUS: 'clients/SET_APPOINTMENTS_TODAY_COMMENT_HIDE_STATUS',
    SET_APPOINTMENTS_COMMENT_HIDE_STATUS: 'clients/SET_APPOINTMENTS_COMMENT_HIDE_STATUS',

    //action
    FETCH_CLIENTS: 'clients/FETCH_CLIENTS',
    FETCH_FILTERED_CLIENTS: 'clients/FETCH_FILTERED_CLIENTS',
    CLEAR_FORM_FIELDS: 'clients/CLEAR_FORM_FIELDS',
    FETCH_CLIENT_DETAILS: 'clients/FETCH_CLIENT_DETAILS',
}