export default {
    //getters
    GET_CLIENTS: 'clients/GET_CLIENTS',
    GET_CLIENT_MODAL_VISIBILITY: 'clients/GET_CLIENT_MODAL_VISIBILITY',
    GET_CLIENT_FORM_FIELDS: 'clients/GET_CLIENT_FORM_FIELDS',
    GET_FETCHING_CLIENTS_STATUS: 'clients/GET_FETCHING_CLIENTS_STATUS',

    //mutation
    SET_CLIENT_MODAL_VISIBILITY: 'clients/SET_CLIENT_MODAL_VISIBILITY',
    SET_MODAL_FIELD_SINGLE_VALUE: 'clients/SET_MODAL_FIELD_SINGLE_VALUE',

    //action
    FETCH_CLIENTS: 'clients/FETCH_CLIENTS',
    FETCH_FILTERED_CLIENTS: 'clients/FETCH_FILTERED_CLIENTS',
    CLEAR_FORM_FIELDS: 'clients/CLEAR_FORM_FIELDS',
}