export default {
    //getters
    GET_VIEW_SCHEDULE_LIST: 'appointment/GET_VIEW_SCHEDULE_LIST',
    GET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/GET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    GET_NEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/GET_NEW_SCHEDULE_MODAL_VISIBILITY',

    //mutation
    SET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/SET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    SET_NEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/SET_NEW_SCHEDULE_MODAL_VISIBILITY',
}