export default {
    //getters
    GET_VIEW_SCHEDULE_LIST: 'appointment/GET_VIEW_SCHEDULE_LIST',
    GET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/GET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    GET_NEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/GET_NEW_SCHEDULE_MODAL_VISIBILITY',
    GET_MODAL_FIELD: 'appointment/GET_MODAL_FIELD',

    //mutation
    SET_MODAL_FIELD_SINGLE_VALUE: 'appointment/SET_MODAL_FIELD_SINGLE_VALUE',
    SET_VIEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/SET_VIEW_SCHEDULE_MODAL_VISIBILITY',
    SET_NEW_SCHEDULE_MODAL_VISIBILITY: 'appointment/SET_NEW_SCHEDULE_MODAL_VISIBILITY',

    //actions
    CLEAR_FORM_FIELDS: 'appointment/CLEAR_FORM_FIELDS',
}