export default {
    //getters
    GET_MODAL_VISIBILITY: 'clinics/GET_MODAL_VISIBILITY',
    GET_CLINICS: 'clinics/GET_CLINICS',
    GET_MODAL_FIELD: 'clinics/GET_MODAL_FIELD',
    GET_FETCHING_CLINICS_STATUS: 'clinics/GET_FETCHING_CLINICS_STATUS',

    //mutation
    SET_MODAL_VISIBILITY: 'clinics/SET_MODAL_VISIBILITY',
    SET_MODAL_FIELD_SINGLE_VALUE: 'clinics/SET_MODAL_FIELD_SINGLE_VALUE',

    //action
    FETCH_CLINICS: 'clinics/FETCH_CLINICS',
    CLEAR_FORM_FIELDS: 'clinics/CLEAR_FORM_FIELDS'
}